import test from "node:test";
import assert from "node:assert/strict";
import { compileCommand, isGeneratedCommand } from "./commands.js";

const source = `---
description: Do the thing
argumentHint: "<topic>"
subtask: true
---

Shared body uses $ARGUMENTS.

<!-- host:claude -->
Claude-only note.
<!-- /host -->

<!-- host:!claude -->
Other-host note.
<!-- /host -->
`;

test("compileCommand maps frontmatter keys per host", () => {
  const claude = compileCommand("demo", source, "claude");
  assert.match(claude, /description: Do the thing/);
  assert.match(claude, /argument-hint/);
  assert.doesNotMatch(claude, /subtask/);

  const opencode = compileCommand("demo", source, "opencode");
  assert.match(opencode, /subtask: true/);
  assert.doesNotMatch(opencode, /argument-hint/);
});

test("compileCommand resolves host guard blocks", () => {
  const claude = compileCommand("demo", source, "claude");
  assert.match(claude, /Claude-only note/);
  assert.doesNotMatch(claude, /Other-host note/);

  const codex = compileCommand("demo", source, "codex");
  assert.doesNotMatch(codex, /Claude-only note/);
  assert.match(codex, /Other-host note/);
});

test("compileCommand stamps a generated banner and is idempotent", () => {
  const first = compileCommand("demo", source, "claude");
  assert.ok(isGeneratedCommand(first));
  assert.equal(compileCommand("demo", source, "claude"), first);
});

test("isGeneratedCommand still recognizes the legacy opetools banner", () => {
  assert.ok(isGeneratedCommand("<!-- generated by opetools skills -->\n\nbody\n"));
});
