import { parseFrontmatter, stringifyFrontmatter } from "./frontmatter.js";
import { applyGuards } from "./guards.js";
import type { CommandHost } from "./types.js";

export const GeneratedSentinel = "generated by skctl";

const legacySentinels = ["generated by opetools skills"];

const bannerFor = (name: string): string =>
  `<!-- ${GeneratedSentinel} — do not edit; edit the source ${name} command and re-sync -->`;

export const isGeneratedCommand = (content: string): boolean =>
  content.includes(GeneratedSentinel) ||
  legacySentinels.some((sentinel) => content.includes(sentinel));

const aliasToNeutral = new Map([
  ["argument-hint", "argumentHint"],
  ["allowed-tools", "allowedTools"],
]);

const neutralToHostKey: Record<CommandHost, Record<string, string>> = {
  claude: {
    description: "description",
    argumentHint: "argument-hint",
    allowedTools: "allowed-tools",
    model: "model",
  },
  opencode: {
    description: "description",
    agent: "agent",
    model: "model",
    subtask: "subtask",
  },
  codex: {
    description: "description",
    argumentHint: "argument-hint",
  },
};

const normalizeKeys = (data: Record<string, unknown>) => {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(data)) {
    out[aliasToNeutral.get(key) ?? key] = value;
  }
  return out;
};

const mapFrontmatter = (
  data: Record<string, unknown>,
  host: CommandHost,
) => {
  const neutral = normalizeKeys(data);
  const keyMap = neutralToHostKey[host];
  const out: Record<string, unknown> = {};
  for (const [neutralKey, hostKey] of Object.entries(keyMap)) {
    if (neutral[neutralKey] !== undefined) out[hostKey] = neutral[neutralKey];
  }
  return out;
};

export const compileCommand = (
  name: string,
  source: string,
  host: CommandHost,
): string => {
  const parsed = parseFrontmatter(source);
  const body = applyGuards(parsed.content, [host]).trim();
  const withBanner = `${bannerFor(name)}\n\n${body}\n`;
  const hostData = mapFrontmatter(parsed.data, host);
  return Object.keys(hostData).length > 0
    ? stringifyFrontmatter(withBanner, hostData)
    : withBanner;
};
