import { parseFrontmatter, stringifyFrontmatter } from "./frontmatter.js";
import type { Host } from "./types.js";

export const GeneratedSentinel = "generated by skctl";

const legacySentinels = ["generated by opetools skills"];

const bannerFor = (name: string): string =>
  `<!-- ${GeneratedSentinel} — do not edit; edit the source ${name} command and re-sync -->`;

export const isGeneratedCommand = (content: string): boolean =>
  content.includes(GeneratedSentinel) ||
  legacySentinels.some((sentinel) => content.includes(sentinel));

const aliasToNeutral: Record<string, string> = {
  "argument-hint": "argumentHint",
  "allowed-tools": "allowedTools",
};

const neutralToHostKey: Record<Host, Record<string, string>> = {
  claude: {
    description: "description",
    argumentHint: "argument-hint",
    allowedTools: "allowed-tools",
    model: "model",
  },
  opencode: {
    description: "description",
    agent: "agent",
    model: "model",
    subtask: "subtask",
  },
  codex: {
    description: "description",
    argumentHint: "argument-hint",
  },
};

const normalizeKeys = (data: Record<string, unknown>): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(data)) {
    out[aliasToNeutral[key] ?? key] = value;
  }
  return out;
};

const mapFrontmatter = (
  data: Record<string, unknown>,
  host: Host,
): Record<string, unknown> => {
  const neutral = normalizeKeys(data);
  const keyMap = neutralToHostKey[host];
  const out: Record<string, unknown> = {};
  for (const [neutralKey, hostKey] of Object.entries(keyMap)) {
    if (neutral[neutralKey] !== undefined) out[hostKey] = neutral[neutralKey];
  }
  return out;
};

const hostMatchesSpec = (spec: string, host: Host): boolean => {
  const negate = spec.startsWith("!");
  const list = (negate ? spec.slice(1) : spec)
    .split(",")
    .map((token) => token.trim())
    .filter(Boolean);
  const inList = list.includes(host);
  return negate ? !inList : inList;
};

const applyHostGuards = (body: string, host: Host): string =>
  body
    .replace(
      /<!--\s*host:([^\n>]+?)\s*-->([\s\S]*?)<!--\s*\/host\s*-->/g,
      (_match, spec: string, inner: string) =>
        hostMatchesSpec(spec.trim(), host) ? inner : "",
    )
    .replace(/\n{3,}/g, "\n\n");

export const compileCommand = (
  name: string,
  source: string,
  host: Host,
): string => {
  const parsed = parseFrontmatter(source);
  const body = applyHostGuards(parsed.content, host).trim();
  const withBanner = `${bannerFor(name)}\n\n${body}\n`;
  const hostData = mapFrontmatter(parsed.data, host);
  return Object.keys(hostData).length > 0
    ? stringifyFrontmatter(withBanner, hostData)
    : withBanner;
};
