import test from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { resolveProjectPaths, resolveSkillPaths } from "./paths.js";
import { defaultManifest, setEnabled } from "./manifest.js";
import { sync } from "./sync.js";

const seedRepo = (home: string): void => {
  const paths = resolveSkillPaths(home);
  mkdirSync(join(paths.sourceSkills, "demo-skill"), { recursive: true });
  writeFileSync(
    join(paths.sourceSkills, "demo-skill", "SKILL.md"),
    "---\nname: demo-skill\ndescription: demo\n---\n\nbody\n",
  );
  mkdirSync(paths.sourceCommands, { recursive: true });
  writeFileSync(
    join(paths.sourceCommands, "demo-cmd.md"),
    "---\ndescription: demo command\n---\n\nRun the thing.\n",
  );
};

test("sync links an enabled skill into agents and claude, and is idempotent", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);

  const agentsLink = join(paths.agentsSkills, "demo-skill");
  const claudeLink = join(paths.claudeSkills, "demo-skill");
  assert.ok(lstatSync(agentsLink).isSymbolicLink());
  assert.ok(lstatSync(claudeLink).isSymbolicLink());
  assert.ok(existsSync(join(agentsLink, "SKILL.md")));

  const second = sync(paths, defaultManifest(), false);
  assert.ok(second.skills.every((action) => action.kind === "ok"));
});

test("sync compiles a command into every default host dir", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);

  for (const host of ["claude", "codex", "opencode"] as const) {
    const file = join(paths.commandDirs[host], "demo-cmd.md");
    assert.ok(existsSync(file), `${host} command missing`);
    assert.match(readFileSync(file, "utf-8"), /generated by skctl/);
  }
});

test("sync prunes generated command files whose source was deleted", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);
  const claudeCmd = join(paths.commandDirs.claude, "demo-cmd.md");
  assert.ok(existsSync(claudeCmd));

  rmSync(join(paths.sourceCommands, "demo-cmd.md"));
  sync(paths, defaultManifest(), false);
  assert.equal(existsSync(claudeCmd), false);
});

test("project scope links skills into .claude without an agents hop, and skips codex commands", () => {
  const root = mkdtempSync(join(tmpdir(), "skctl-project-"));
  mkdirSync(join(root, ".agents", "skills", "proj-skill"), { recursive: true });
  writeFileSync(
    join(root, ".agents", "skills", "proj-skill", "SKILL.md"),
    "---\nname: proj-skill\ndescription: demo\n---\n\nbody\n",
  );
  mkdirSync(join(root, ".agents", "commands"), { recursive: true });
  writeFileSync(
    join(root, ".agents", "commands", "proj-cmd.md"),
    "---\ndescription: project command\n---\n\nDo it.\n",
  );
  const paths = resolveProjectPaths(root);

  sync(paths, defaultManifest(), false);

  const claudeSkill = join(root, ".claude", "skills", "proj-skill");
  assert.ok(lstatSync(claudeSkill).isSymbolicLink());
  assert.ok(existsSync(join(claudeSkill, "SKILL.md")));
  assert.equal(
    lstatSync(join(root, ".agents", "skills", "proj-skill")).isSymbolicLink(),
    false,
  );
  assert.ok(existsSync(join(root, ".claude", "commands", "proj-cmd.md")));
  assert.ok(existsSync(join(root, ".opencode", "commands", "proj-cmd.md")));
  assert.equal(existsSync(join(root, ".codex", "prompts", "proj-cmd.md")), false);
});

test("disabling a skill removes its links but leaves the source", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);
  const disabled = setEnabled(defaultManifest(), "skills", "demo-skill", false);
  sync(paths, disabled, false);

  assert.equal(existsSync(join(paths.agentsSkills, "demo-skill")), false);
  assert.equal(existsSync(join(paths.claudeSkills, "demo-skill")), false);
  assert.ok(existsSync(join(paths.sourceSkills, "demo-skill", "SKILL.md")));
});
