import test from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { resolveProjectPaths, resolveSkillPaths } from "./paths.js";
import { pathPresent } from "./fsx.js";
import { defaultManifest, setEnabled } from "./manifest.js";
import { sync } from "./sync.js";
import type { CommandHost, Surface } from "./types.js";

const commandHosts: CommandHost[] = ["claude", "codex", "opencode"];
const sharedSurfaces: Surface[] = ["claude", "agents"];

const seedRepo = (home: string): void => {
  const paths = resolveSkillPaths(home);
  mkdirSync(join(paths.sourceSkills, "demo-skill"), { recursive: true });
  writeFileSync(
    join(paths.sourceSkills, "demo-skill", "SKILL.md"),
    "---\nname: demo-skill\ndescription: demo\n---\n\nbody\n",
  );
  mkdirSync(paths.sourceCommands, { recursive: true });
  writeFileSync(
    join(paths.sourceCommands, "demo-cmd.md"),
    "---\ndescription: demo command\n---\n\nRun the thing.\n",
  );
};

test("sync links an enabled skill into agents and claude, and is idempotent", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);

  const agentsLink = join(paths.surfaceDirs.agents, "demo-skill");
  const claudeLink = join(paths.surfaceDirs.claude, "demo-skill");
  assert.ok(lstatSync(agentsLink).isSymbolicLink());
  assert.ok(lstatSync(claudeLink).isSymbolicLink());
  assert.ok(existsSync(join(agentsLink, "SKILL.md")));

  const second = sync(paths, defaultManifest(), false);
  assert.ok(second.skills.every((action) => action.kind === "ok"));
});

test("sync compiles a command into every default host dir", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);

  for (const host of commandHosts) {
    const file = join(paths.commandDirs[host], "demo-cmd.md");
    assert.ok(existsSync(file), `${host} command missing`);
    assert.match(readFileSync(file, "utf-8"), /generated by skctl/);
  }
});

test("sync prunes generated command files whose source was deleted", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);
  const claudeCmd = join(paths.commandDirs.claude, "demo-cmd.md");
  assert.ok(existsSync(claudeCmd));

  rmSync(join(paths.sourceCommands, "demo-cmd.md"));
  sync(paths, defaultManifest(), false);
  assert.equal(existsSync(claudeCmd), false);
});

test("project scope links skills into .claude without an agents hop, and skips codex commands", () => {
  const root = mkdtempSync(join(tmpdir(), "skctl-project-"));
  mkdirSync(join(root, ".agents", "skills", "proj-skill"), { recursive: true });
  writeFileSync(
    join(root, ".agents", "skills", "proj-skill", "SKILL.md"),
    "---\nname: proj-skill\ndescription: demo\n---\n\nbody\n",
  );
  mkdirSync(join(root, ".agents", "commands"), { recursive: true });
  writeFileSync(
    join(root, ".agents", "commands", "proj-cmd.md"),
    "---\ndescription: project command\n---\n\nDo it.\n",
  );
  const paths = resolveProjectPaths(root);

  sync(paths, defaultManifest(), false);

  const claudeSkill = join(root, ".claude", "skills", "proj-skill");
  assert.ok(lstatSync(claudeSkill).isSymbolicLink());
  assert.ok(existsSync(join(claudeSkill, "SKILL.md")));
  assert.equal(
    lstatSync(join(root, ".agents", "skills", "proj-skill")).isSymbolicLink(),
    false,
  );
  assert.ok(existsSync(join(root, ".claude", "commands", "proj-cmd.md")));
  assert.ok(existsSync(join(root, ".opencode", "commands", "proj-cmd.md")));
  assert.equal(existsSync(join(root, ".codex", "prompts", "proj-cmd.md")), false);
});

test("disabling a skill removes its links but leaves the source", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);
  const disabled = setEnabled(defaultManifest(), "skills", "demo-skill", false);
  sync(paths, disabled, false);

  assert.equal(existsSync(join(paths.surfaceDirs.agents, "demo-skill")), false);
  assert.equal(existsSync(join(paths.surfaceDirs.claude, "demo-skill")), false);
  assert.ok(existsSync(join(paths.sourceSkills, "demo-skill", "SKILL.md")));
});

test("sync compiles a skill per surface and points the host link at the build", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);
  writeFileSync(
    join(paths.sourceSkills, "demo-skill", "SKILL.md"),
    "---\nname: demo-skill\ndescription: demo\npaste: true\n---\n\nbody\n",
  );

  sync(paths, defaultManifest(), false);

  for (const surface of sharedSurfaces) {
    const compiled = join(paths.buildDir, surface, "demo-skill", "SKILL.md");
    assert.ok(existsSync(compiled), `${surface} build missing`);
    assert.doesNotMatch(readFileSync(compiled, "utf-8"), /paste/);
  }
  const link = join(paths.surfaceDirs.claude, "demo-skill");
  assert.ok(lstatSync(link).isSymbolicLink());
  assert.equal(
    realpathSync(link),
    realpathSync(join(paths.buildDir, "claude", "demo-skill")),
  );
});

test("a bundled sibling stays reachable through the build directory", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);
  mkdirSync(join(paths.sourceSkills, "demo-skill", "scripts"), { recursive: true });
  writeFileSync(join(paths.sourceSkills, "demo-skill", "scripts", "run.sh"), "echo hi\n");

  sync(paths, defaultManifest(), false);

  const viaLink = join(paths.surfaceDirs.agents, "demo-skill", "scripts", "run.sh");
  assert.equal(readFileSync(viaLink, "utf-8"), "echo hi\n");
});

test("an overlay reshapes the body and can differ per surface", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);
  writeFileSync(
    join(paths.sourceSkills, "demo-skill", "SKILL.md"),
    "---\nname: demo-skill\ndescription: demo\n---\n\nuse Cursor for this\n",
  );
  mkdirSync(paths.overlaysDir, { recursive: true });
  writeFileSync(
    join(paths.overlaysDir, "demo-skill.md"),
    "---\nreplace:\n  Cursor: the agent\nclaude:\n  set:\n    context: fork\n---\n\nwhy\n",
  );

  sync(paths, defaultManifest(), false);

  const claude = readFileSync(join(paths.buildDir, "claude", "demo-skill", "SKILL.md"), "utf-8");
  const agents = readFileSync(join(paths.buildDir, "agents", "demo-skill", "SKILL.md"), "utf-8");
  assert.match(claude, /use the agent for this/);
  assert.match(agents, /use the agent for this/);
  assert.match(claude, /context: fork/);
  assert.doesNotMatch(agents, /context/);
});

const divergenceReports = (home: string): string[] => {
  const report = sync(resolveSkillPaths(home), defaultManifest(), false);
  return report.skills
    .filter((action) => /instructions differ/.test(action.detail))
    .map((action) => action.detail)
    .sort();
};

test("a body that differs per surface reports the clients reading both copies", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);
  writeFileSync(
    join(paths.sourceSkills, "demo-skill", "SKILL.md"),
    [
      "---",
      "name: demo-skill",
      "description: demo",
      "---",
      "",
      "<!-- host:claude -->",
      "read @notes.md",
      "<!-- /host -->",
    ].join("\n"),
  );

  assert.deepEqual(divergenceReports(home), [
    "cursor reads 2 variants whose instructions differ",
    "opencode reads 2 variants whose instructions differ",
  ]);
});

// Frontmatter differing across surfaces is the whole point of compiling per surface, and every
// client ignores or accepts what it does not use, so it must not be reported as a problem.
test("frontmatter that differs per surface is not reported as divergence", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);
  mkdirSync(paths.overlaysDir, { recursive: true });
  writeFileSync(
    join(paths.overlaysDir, "demo-skill.md"),
    "---\nclaude:\n  set:\n    context: fork\n---\n",
  );

  assert.deepEqual(divergenceReports(home), []);
  assert.match(
    readFileSync(join(paths.buildDir, "claude", "demo-skill", "SKILL.md"), "utf-8"),
    /context: fork/,
  );
});

test("deleting a skill from source clears its build and its links", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);

  sync(paths, defaultManifest(), false);
  assert.ok(existsSync(join(paths.buildDir, "agents", "demo-skill")));

  rmSync(join(paths.sourceSkills, "demo-skill"), { recursive: true });
  sync(paths, defaultManifest(), false);

  assert.equal(existsSync(join(paths.buildDir, "agents", "demo-skill")), false);
  assert.equal(pathPresent(join(paths.surfaceDirs.agents, "demo-skill")), false);
  assert.equal(pathPresent(join(paths.surfaceDirs.claude, "demo-skill")), false);
});

test("apply ignores the build directory in the skills root", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);
  writeFileSync(paths.gitignorePath, ".DS_Store\n");

  sync(paths, defaultManifest(), false);

  const ignored = readFileSync(paths.gitignorePath, "utf-8");
  assert.match(ignored, /^\.DS_Store$/m);
  assert.match(ignored, /^\.build\/$/m);

  sync(paths, defaultManifest(), false);
  assert.equal(ignored.match(/\.build\//g)?.length, 1);
});

test("tagged skills materialize only when one of their tags is active", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-sync-"));
  seedRepo(home);
  const paths = resolveSkillPaths(home);
  const manifest = {
    ...defaultManifest(),
    skills: { "demo-skill": { tags: ["work"] } },
  };

  sync(paths, manifest, false);
  assert.equal(existsSync(join(paths.surfaceDirs.agents, "demo-skill")), false);

  sync(paths, manifest, false, ["work"]);
  assert.ok(existsSync(join(paths.surfaceDirs.agents, "demo-skill", "SKILL.md")));
});
