import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { generateRaycastScripts, syncRaycast } from "./raycast.js";

test("the scripts take a free-text skill argument and name no skill", () => {
  const paste = generateRaycastScripts().find((s) => s.filename === "skctl-paste.sh");
  assert.ok(paste);
  assert.match(paste.content, /generated by skctl/);
  assert.match(paste.content, /@raycast\.argument1 \{"type":"text","placeholder":"skill"\}/);
  assert.doesNotMatch(paste.content, /dropdown/);
});

test("the scripts stay identical as the skill list changes", () => {
  const before = generateRaycastScripts();
  const home = mkdtempSync(join(tmpdir(), "skctl-raycast-"));
  mkdirSync(join(home, ".agents", "skills", "newcomer"), { recursive: true });
  writeFileSync(
    join(home, ".agents", "skills", "newcomer", "SKILL.md"),
    "---\nname: newcomer\n---\n\nbody\n",
  );

  assert.deepEqual(generateRaycastScripts(), before);
});

test("every script forces a UTF-8 locale so pbcopy preserves non-ASCII bodies", () => {
  for (const script of generateRaycastScripts()) {
    assert.match(script.content, /^export LC_CTYPE="UTF-8"$/m, script.filename);
    assert.match(script.content, /^unset LC_ALL$/m, script.filename);
  }
});

test("syncRaycast writes executable scripts, is idempotent, and refuses foreign files", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-raycast-"));
  const target = join(home, "raycast");

  const created = syncRaycast(target);
  assert.ok(created.every((a) => a.kind === "created"));
  const paste = join(target, "skctl-paste.sh");
  assert.ok(existsSync(paste));
  assert.ok((statSync(paste).mode & 0o100) !== 0, "paste script should be executable");

  assert.ok(syncRaycast(target).every((a) => a.kind === "ok"));

  writeFileSync(join(target, "skctl-apply.sh"), "#!/bin/bash\necho hand-written\n");
  assert.ok(syncRaycast(target).some((a) => a.kind === "conflict"));
});
