import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { configPath } from "./config.js";
import { listSkills } from "./skills/inspect.js";
import type { SkillInfo } from "./skills/inspect.js";
import type { Action } from "./skills/types.js";
import type { SkillPaths } from "./skills/paths.js";

export const RaycastSentinel = "generated by skctl";

export interface RaycastScript {
  filename: string;
  content: string;
}

export const defaultRaycastDir = (): string =>
  join(dirname(configPath()), "raycast");

const preamble = [
  `# ${RaycastSentinel} — do not edit; regenerate with \`skctl raycast sync\``,
  "",
  "# pbcopy/pbpaste fall back to the C encoding when no locale is set, mangling non-ASCII",
  "unset LC_ALL",
  `export LC_CTYPE="UTF-8"`,
  `export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"`,
  "if ! command -v node >/dev/null 2>&1; then",
  `  for dir in "$HOME"/.nvm/versions/node/*/bin; do`,
  `    [ -x "$dir/node" ] && export PATH="$dir:$PATH"`,
  "  done",
  "fi",
  "if ! command -v skctl >/dev/null 2>&1; then",
  `  echo "skctl not found on PATH"`,
  "  exit 1",
  "fi",
].join("\n");

interface ScriptSpec {
  filename: string;
  title: string;
  mode: "silent" | "fullOutput";
  icon: string;
  description: string;
  argument?: string;
  body: string;
}

const render = (spec: ScriptSpec): RaycastScript => {
  const header = [
    "#!/bin/bash",
    "# @raycast.schemaVersion 1",
    `# @raycast.title ${spec.title}`,
    `# @raycast.mode ${spec.mode}`,
    "# @raycast.packageName Skctl",
    `# @raycast.icon ${spec.icon}`,
    ...(spec.argument ? [`# @raycast.argument1 ${spec.argument}`] : []),
    `# @raycast.description ${spec.description}`,
  ].join("\n");
  return {
    filename: spec.filename,
    content: `${header}\n${preamble}\n\n${spec.body}\n`,
  };
};

// Raycast parses an argument's dropdown data from the script header before the script
// runs, so the skill list has to be baked in. That means these files are rewritten
// whenever the list changes, which is why apply syncs them without reporting it.
const skillDropdown = (skills: SkillInfo[]): string => {
  const data = skills.map((skill) => {
    const markers = [
      skill.remote ? `[${skill.remote}]` : "",
      skill.paste ? "[paste]" : "",
      skill.enabled ? "" : "(disabled)",
    ]
      .filter(Boolean)
      .join(" ");
    return { title: markers ? `${skill.name}  ${markers}` : skill.name, value: skill.name };
  });
  return JSON.stringify({ type: "dropdown", placeholder: "skill", data });
};

const pasteBody = `name="$1"
content="$(skctl get skill "$name" -o body 2>/dev/null)"
if [ -z "$content" ]; then
  echo "Unknown skill: $name"
  exit 1
fi
previous="$(pbpaste)"
printf '%s' "$content" | pbcopy
osascript -e 'tell application "System Events" to keystroke "v" using command down'
sleep 0.25
printf '%s' "$previous" | pbcopy
echo "Pasted skill: $name"`;

export const generateRaycastScripts = (
  paths: SkillPaths,
  activeTags: readonly string[] = [],
): RaycastScript[] => {
  const skills = listSkills(paths, false, activeTags);
  const dropdown = skillDropdown(skills);
  const pasteDropdown = skillDropdown(
    skills.filter((skill) => skill.paste).length > 0
      ? [...skills].sort((a, b) => Number(b.paste) - Number(a.paste))
      : skills,
  );
  return [
    render({
      filename: "skctl-apply.sh",
      title: "Apply Skills",
      mode: "fullOutput",
      icon: "🔁",
      description: "Materialize the manifest into every host (symlinks + compiled commands)",
      body: "skctl apply",
    }),
    render({
      filename: "skctl-get-skills.sh",
      title: "List Skills",
      mode: "fullOutput",
      icon: "📜",
      description: "Show every skill with its state, target hosts, and paste flag",
      body: "skctl get skills",
    }),
    render({
      filename: "skctl-paste.sh",
      title: "Paste Skill",
      mode: "silent",
      icon: "📋",
      description: "Paste a skill's body into the focused input",
      argument: pasteDropdown,
      body: pasteBody,
    }),
    render({
      filename: "skctl-describe.sh",
      title: "Describe Skill",
      mode: "fullOutput",
      icon: "🔎",
      description: "Show a skill's state, hosts, and description",
      argument: dropdown,
      body: `skctl describe skill "$1"`,
    }),
  ];
};

const isGenerated = (content: string): boolean => content.includes(RaycastSentinel);

const write = (dest: string, content: string): void => {
  writeFileSync(dest, content, "utf-8");
  chmodSync(dest, 0o755);
};

export const syncRaycast = (
  paths: SkillPaths,
  targetDir: string,
  activeTags: readonly string[] = [],
): Action[] => {
  mkdirSync(targetDir, { recursive: true });
  return generateRaycastScripts(paths, activeTags).map((script) => {
    const dest = join(targetDir, script.filename);
    if (existsSync(dest)) {
      const current = readFileSync(dest, "utf-8");
      if (current === script.content) return { kind: "ok", detail: dest, subject: script.filename };
      if (!isGenerated(current)) {
        return {
          kind: "conflict",
          detail: dest,
          subject: script.filename,
          note: "exists and was not generated",
        };
      }
      write(dest, script.content);
      return { kind: "replaced", detail: dest, subject: script.filename };
    }
    write(dest, script.content);
    return { kind: "created", detail: dest, subject: script.filename };
  });
};
