import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { resolveSkillPaths } from "./skills/paths.js";
import { generateRaycastScripts, syncRaycast } from "./raycast.js";

const seedSkill = (home: string, name: string): void => {
  const paths = resolveSkillPaths(home);
  mkdirSync(join(paths.sourceSkills, name), { recursive: true });
  writeFileSync(
    join(paths.sourceSkills, name, "SKILL.md"),
    `---\nname: ${name}\ndescription: d\n---\n\nbody\n`,
  );
};

test("generateRaycastScripts bakes the skill list into the paste dropdown", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-raycast-"));
  seedSkill(home, "commit");
  const paths = resolveSkillPaths(home);

  const paste = generateRaycastScripts(paths).find((s) => s.filename === "skctl-paste.sh");
  assert.ok(paste);
  assert.match(paste.content, /generated by skctl/);
  assert.match(paste.content, /@raycast\.argument1/);
  assert.match(paste.content, /"value":"commit"/);
});

test("syncRaycast writes executable scripts, is idempotent, and refuses foreign files", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-raycast-"));
  mkdirSync(resolveSkillPaths(home).sourceSkills, { recursive: true });
  const paths = resolveSkillPaths(home);
  const target = join(home, "raycast");

  const created = syncRaycast(paths, target);
  assert.ok(created.every((a) => a.kind === "created"));
  const paste = join(target, "skctl-paste.sh");
  assert.ok(existsSync(paste));
  assert.ok((statSync(paste).mode & 0o100) !== 0, "paste script should be executable");

  assert.ok(syncRaycast(paths, target).every((a) => a.kind === "ok"));

  writeFileSync(join(target, "skctl-apply.sh"), "#!/bin/bash\necho hand-written\n");
  assert.ok(syncRaycast(paths, target).some((a) => a.kind === "conflict"));
});
