import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { resolveSkillPaths } from "./skills/paths.js";
import { generateRaycastScripts, syncRaycast } from "./raycast.js";

const seedSkill = (home: string, name: string, paste = false): void => {
  const paths = resolveSkillPaths(home);
  mkdirSync(join(paths.sourceSkills, name), { recursive: true });
  writeFileSync(
    join(paths.sourceSkills, name, "SKILL.md"),
    `---\nname: ${name}\ndescription: d\n${paste ? "paste: true\n" : ""}---\n\nbody\n`,
  );
};

const pasteScript = (home: string): string => {
  const script = generateRaycastScripts(resolveSkillPaths(home)).find(
    (s) => s.filename === "skctl-paste.sh",
  );
  assert.ok(script);
  return script.content;
};

test("generateRaycastScripts bakes the skill list into the paste dropdown", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-raycast-"));
  seedSkill(home, "commit");

  const content = pasteScript(home);
  assert.match(content, /generated by skctl/);
  assert.match(content, /@raycast\.argument1/);
  assert.match(content, /"value":"commit"/);
});

test("paste-flagged skills sort first and carry the paste marker", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-raycast-"));
  seedSkill(home, "alpha");
  seedSkill(home, "zeta", true);

  const content = pasteScript(home);
  assert.match(content, /zeta {2}\[paste\]/);
  assert.ok(
    content.indexOf('"value":"zeta"') < content.indexOf('"value":"alpha"'),
    "the paste-flagged skill should come first in the dropdown",
  );
});

test("every script forces a UTF-8 locale so pbcopy preserves non-ASCII bodies", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-raycast-"));
  seedSkill(home, "commit");

  for (const script of generateRaycastScripts(resolveSkillPaths(home))) {
    assert.match(script.content, /^export LC_CTYPE="UTF-8"$/m, script.filename);
    assert.match(script.content, /^unset LC_ALL$/m, script.filename);
  }
});

test("syncRaycast writes executable scripts, is idempotent, and refuses foreign files", () => {
  const home = mkdtempSync(join(tmpdir(), "skctl-raycast-"));
  mkdirSync(resolveSkillPaths(home).sourceSkills, { recursive: true });
  const paths = resolveSkillPaths(home);
  const target = join(home, "raycast");

  const created = syncRaycast(paths, target);
  assert.ok(created.every((a) => a.kind === "created"));
  const paste = join(target, "skctl-paste.sh");
  assert.ok(existsSync(paste));
  assert.ok((statSync(paste).mode & 0o100) !== 0, "paste script should be executable");

  assert.ok(syncRaycast(paths, target).every((a) => a.kind === "ok"));

  writeFileSync(join(target, "skctl-apply.sh"), "#!/bin/bash\necho hand-written\n");
  assert.ok(syncRaycast(paths, target).some((a) => a.kind === "conflict"));
});
